name: Update Beamline Plugin Repositories
on:
  workflow_dispatch

jobs:
  update_beamline_plugins:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo_name: ${{ fromJSON(vars.BEAMLINE_REPO_NAMES) }}
    steps:
      - uses: ./.github/actions/trigger_child_update
        with:
          REPO_NAME: ${{ matrix.repo_name }}
    

